# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='from_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchangerate_from', to='gatherings.Currency'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='to_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchangerate_to', to='gatherings.Currency'),
        ),
    ]
